import { Aliment } from 'src/modules/aliment/entities/aliment.entity';
import { DataSource } from 'typeorm';
import { Seeder, SeederFactoryManager } from 'typeorm-extension';

export default class AlimentSeeder implements Seeder {
  public async run(
    dataSource: DataSource,
    factoryManager: SeederFactoryManager,
  ): Promise<any> {
    //console.log('Objection status seeder');
    const repository = dataSource.getRepository(Aliment);

    const aliment = await repository.create([
      {
        name: 'Huevo',
        description: 'Huevo de gallina',
        calories_portion: 78,
        protein_portion: 6.3,
        carbos_portion: 0.6,
        fats_portion: 5.3,
      },
      {
        name: 'Arroz blanco',
        description: 'Arroz de grano largo cocido',
        calories_portion: 130,
        protein_portion: 2.4,
        carbos_portion: 28,
        fats_portion: 0.2,
      },
      {
        name: 'Lechuga',
        description: 'Lechuga verde',
        calories_portion: 5,
        protein_portion: 0.5,
        carbos_portion: 1,
        fats_portion: 0.1,
      },
      {
        name: 'Pollo',
        description: 'Pechuga de pollo',
        calories_portion: 165,
        protein_portion: 31,
        carbos_portion: 0,
        fats_portion: 3.6,
      },
      {
        name: 'Carne de res magra',
        description: 'Carne de res magra cocida',
        calories_portion: 250,
        protein_portion: 25,
        carbos_portion: 0,
        fats_portion: 15,
      },
      {
        name: 'Salmón',
        description: 'Filete de salmón al horno',
        calories_portion: 206,
        protein_portion: 22,
        carbos_portion: 0,
        fats_portion: 13,
      },
      {
        name: 'Atún enlatado',
        description: 'Atún enlatado en agua',
        calories_portion: 110,
        protein_portion: 24,
        carbos_portion: 0,
        fats_portion: 1,
      },
      {
        name: 'Manzana',
        description: 'Manzana roja',
        calories_portion: 52,
        protein_portion: 0.3,
        carbos_portion: 14,
        fats_portion: 0.2,
      },
      {
        name: 'Banana',
        description: 'Banana madura',
        calories_portion: 105,
        protein_portion: 1.3,
        carbos_portion: 27,
        fats_portion: 0.4,
      },
      {
        name: 'Zanahoria',
        description: 'Zanahoria cruda',
        calories_portion: 25,
        protein_portion: 0.6,
        carbos_portion: 6,
        fats_portion: 0.1,
      },
      {
        name: 'Papa',
        description: 'Papa blanca cocida',
        calories_portion: 163,
        protein_portion: 3.6,
        carbos_portion: 37,
        fats_portion: 0.2,
      },
      {
        name: 'Pasta',
        description: 'Pasta de trigo cocida',
        calories_portion: 131,
        protein_portion: 5,
        carbos_portion: 25,
        fats_portion: 1.1,
      },
      {
        name: 'Pan integral',
        description: 'Pan integral rebanado',
        calories_portion: 69,
        protein_portion: 3,
        carbos_portion: 12,
        fats_portion: 1,
      },
      {
        name: 'Yogur natural',
        description: 'Yogur natural bajo en grasa',
        calories_portion: 59,
        protein_portion: 10,
        carbos_portion: 4.7,
        fats_portion: 0.4,
      },
      {
        name: 'Queso cheddar',
        description: 'Queso cheddar rallado',
        calories_portion: 113,
        protein_portion: 7,
        carbos_portion: 0.4,
        fats_portion: 9,
      },
      {
        name: 'Cacahuetes',
        description: 'Cacahuetes tostados sin sal',
        calories_portion: 166,
        protein_portion: 7,
        carbos_portion: 6,
        fats_portion: 14,
      },
      {
        name: 'Aceite de oliva',
        description: 'Aceite de oliva virgen extra',
        calories_portion: 119,
        protein_portion: 0,
        carbos_portion: 0,
        fats_portion: 13.5,
      },
      {
        name: 'Mantequilla',
        description: 'Mantequilla sin sal',
        calories_portion: 102,
        protein_portion: 0.1,
        carbos_portion: 0.1,
        fats_portion: 11.5,
      },
      {
        name: 'Aguacate',
        description: 'Aguacate Hass',
        calories_portion: 160,
        protein_portion: 2,
        carbos_portion: 8.5,
        fats_portion: 14.7,
      },
      {
        name: 'Fresas',
        description: 'Fresas frescas',
        calories_portion: 32,
        protein_portion: 0.7,
        carbos_portion: 7.7,
        fats_portion: 0.3,
      },
      {
        name: 'Brócoli',
        description: 'Brócoli crudo',
        calories_portion: 34,
        protein_portion: 2.8,
        carbos_portion: 6,
        fats_portion: 0.4,
      },
      {
        name: 'Tomate',
        description: 'Tomate fresco',
        calories_portion: 18,
        protein_portion: 0.9,
        carbos_portion: 3.9,
        fats_portion: 0.2,
      },
      {
        name: 'Pavo',
        description: 'Pavo molido magro cocido',
        calories_portion: 146,
        protein_portion: 29,
        carbos_portion: 0,
        fats_portion: 2,
      },
      {
        name: 'Ternera molida',
        description: 'Carne de ternera molida magra cocida',
        calories_portion: 250,
        protein_portion: 25,
        carbos_portion: 0,
        fats_portion: 15,
      },
      {
        name: 'Cerdo',
        description: 'Lomo de cerdo magro cocido',
        calories_portion: 143,
        protein_portion: 22,
        carbos_portion: 0,
        fats_portion: 6,
      },
      {
        name: 'Frijoles negros',
        description: 'Frijoles negros cocidos',
        calories_portion: 227,
        protein_portion: 15,
        carbos_portion: 41,
        fats_portion: 0.9,
      },
      {
        name: 'Cuscús',
        description: 'Cuscús cocido',
        calories_portion: 176,
        protein_portion: 5.8,
        carbos_portion: 36,
        fats_portion: 0.2,
      },
      {
        name: 'Tofu',
        description: 'Tofu firme',
        calories_portion: 76,
        protein_portion: 8,
        carbos_portion: 1.9,
        fats_portion: 4.8,
      },
      {
        name: 'Almendras',
        description: 'Almendras crudas',
        calories_portion: 207,
        protein_portion: 7.6,
        carbos_portion: 7.6,
        fats_portion: 18.6,
      },
      {
        name: 'Espinacas',
        description: 'Espinacas frescas',
        calories_portion: 23,
        protein_portion: 2.9,
        carbos_portion: 3.6,
        fats_portion: 0.4,
      },
      {
        name: 'Avena',
        description: 'Avena cocida',
        calories_portion: 145,
        protein_portion: 5.5,
        carbos_portion: 25,
        fats_portion: 2,
      },
      {
        name: 'Cereza',
        description: 'Cereza fresca',
        calories_portion: 50,
        protein_portion: 1,
        carbos_portion: 12,
        fats_portion: 0.3,
      },
      {
        name: 'Piña',
        description: 'Piña fresca',
        calories_portion: 50,
        protein_portion: 0.5,
        carbos_portion: 13,
        fats_portion: 0.1,
      },
      {
        name: 'Pechuga de pavo',
        description: 'Pechuga de pavo cocida',
        calories_portion: 135,
        protein_portion: 30,
        carbos_portion: 0,
        fats_portion: 1,
      },
      {
        name: 'Canela',
        description: 'Canela molida',
        calories_portion: 6,
        protein_portion: 0.1,
        carbos_portion: 2.1,
        fats_portion: 0.1,
      },
      {
        name: 'Nuez',
        description: 'Nuez cruda',
        calories_portion: 185,
        protein_portion: 4.3,
        carbos_portion: 3.9,
        fats_portion: 18.5,
      },
      {
        name: 'Melocotón',
        description: 'Melocotón fresco',
        calories_portion: 39,
        protein_portion: 0.9,
        carbos_portion: 10,
        fats_portion: 0.3,
      },
      {
        name: 'Cebolla',
        description: 'Cebolla cruda',
        calories_portion: 40,
        protein_portion: 1.1,
        carbos_portion: 9.3,
        fats_portion: 0.1,
      },
      {
        name: 'Salmón ahumado',
        description: 'Salmón ahumado',
        calories_portion: 117,
        protein_portion: 15,
        carbos_portion: 0,
        fats_portion: 6,
      },
      {
        name: 'Hamburguesa de res',
        description: 'Hamburguesa de res cocida',
        calories_portion: 220,
        protein_portion: 20,
        carbos_portion: 0,
        fats_portion: 15,
      },
      {
        name: 'Pavo asado',
        description: 'Pavo asado sin piel',
        calories_portion: 135,
        protein_portion: 25,
        carbos_portion: 0,
        fats_portion: 2,
      },
      {
        name: 'Trucha',
        description: 'Filete de trucha cocido',
        calories_portion: 148,
        protein_portion: 22,
        carbos_portion: 0,
        fats_portion: 6,
      },
      {
        name: 'Chocolate negro',
        description: 'Chocolate negro (70-85% cacao)',
        calories_portion: 170,
        protein_portion: 2,
        carbos_portion: 13,
        fats_portion: 12,
      },
      {
        name: 'Queso mozzarella',
        description: 'Queso mozzarella rallado',
        calories_portion: 85,
        protein_portion: 6,
        carbos_portion: 1,
        fats_portion: 6,
      },
      {
        name: 'Pan integral',
        description: 'Pan integral rebanado',
        calories_portion: 69,
        protein_portion: 3,
        carbos_portion: 12,
        fats_portion: 1,
      },
      {
        name: 'Hummus',
        description: 'Hummus de garbanzos',
        calories_portion: 166,
        protein_portion: 8,
        carbos_portion: 9,
        fats_portion: 12,
      },
      {
        name: 'Pasta de almendras',
        description: 'Pasta de almendras',
        calories_portion: 180,
        protein_portion: 7,
        carbos_portion: 6,
        fats_portion: 15,
      },
      {
        name: 'Hojuelas de avena',
        description: 'Hojuelas de avena cruda',
        calories_portion: 68,
        protein_portion: 2.3,
        carbos_portion: 12,
        fats_portion: 1.4,
      },
      {
        name: 'Mango',
        description: 'Mango fresco',
        calories_portion: 60,
        protein_portion: 0.8,
        carbos_portion: 15,
        fats_portion: 0.4,
      },
      {
        name: 'Kiwi',
        description: 'Kiwi fresco',
        calories_portion: 42,
        protein_portion: 0.8,
        carbos_portion: 10,
        fats_portion: 0.4,
      },
      {
        name: 'Ciruela',
        description: 'Ciruela fresca',
        calories_portion: 46,
        protein_portion: 0.7,
        carbos_portion: 11,
        fats_portion: 0.3,
      },
      {
        name: 'Pera',
        description: 'Pera fresca',
        calories_portion: 58,
        protein_portion: 0.4,
        carbos_portion: 15,
        fats_portion: 0.2,
      },
      {
        name: 'Miel',
        description: 'Miel natural',
        calories_portion: 304,
        protein_portion: 0.3,
        carbos_portion: 82,
        fats_portion: 0,
      },
      {
        name: 'Galletas de avena',
        description: 'Galletas de avena',
        calories_portion: 110,
        protein_portion: 1.7,
        carbos_portion: 19,
        fats_portion: 3.3,
      },
      {
        name: 'Pepino',
        description: 'Pepino fresco',
        calories_portion: 15,
        protein_portion: 0.7,
        carbos_portion: 3.6,
        fats_portion: 0.1,
      },
      {
        name: 'Jengibre',
        description: 'Jengibre fresco',
        calories_portion: 80,
        protein_portion: 1.8,
        carbos_portion: 18,
        fats_portion: 0.8,
      },
      {
        name: 'Limón',
        description: 'Limón fresco',
        calories_portion: 29,
        protein_portion: 1.1,
        carbos_portion: 9,
        fats_portion: 0.3,
      },
      {
        name: 'Frambuesa',
        description: 'Frambuesa fresca',
        calories_portion: 52,
        protein_portion: 1.5,
        carbos_portion: 12,
        fats_portion: 0.7,
      },
      {
        name: 'Arándano',
        description: 'Arándano fresco',
        calories_portion: 57,
        protein_portion: 0.7,
        carbos_portion: 15,
        fats_portion: 0.3,
      },
      {
        name: 'Naranja',
        description: 'Naranja fresca',
        calories_portion: 43,
        protein_portion: 0.9,
        carbos_portion: 9,
        fats_portion: 0.1,
      },
      {
        name: 'Pechuga de pato',
        description: 'Pechuga de pato cocida',
        calories_portion: 137,
        protein_portion: 18,
        carbos_portion: 0,
        fats_portion: 7,
      },
      {
        name: 'Ciruela pasa',
        description: 'Ciruela pasa deshidratada',
        calories_portion: 46,
        protein_portion: 0.7,
        carbos_portion: 12,
        fats_portion: 0,
      },
      {
        name: 'Queso parmesano',
        description: 'Queso parmesano rallado',
        calories_portion: 420,
        protein_portion: 35,
        carbos_portion: 4,
        fats_portion: 29,
      },
      {
        name: 'Queso de cabra',
        description: 'Queso de cabra fresco',
        calories_portion: 364,
        protein_portion: 21,
        carbos_portion: 3.2,
        fats_portion: 29,
      },
      {
        name: 'Cacao en polvo',
        description: 'Cacao en polvo sin azúcar',
        calories_portion: 12,
        protein_portion: 1.3,
        carbos_portion: 3.1,
        fats_portion: 0.7,
      },
      {
        name: 'Higos',
        description: 'Higos frescos',
        calories_portion: 74,
        protein_portion: 1.3,
        carbos_portion: 19,
        fats_portion: 0.3,
      },
      {
        name: 'Ajo',
        description: 'Ajo fresco',
        calories_portion: 149,
        protein_portion: 6.4,
        carbos_portion: 33,
        fats_portion: 0.5,
      },
      {
        name: 'Apio',
        description: 'Apio fresco',
        calories_portion: 18,
        protein_portion: 0.8,
        carbos_portion: 4.4,
        fats_portion: 0.2,
      },
      {
        name: 'Nuez de Brasil',
        description: 'Nuez de Brasil cruda',
        calories_portion: 184,
        protein_portion: 4.1,
        carbos_portion: 2.3,
        fats_portion: 18.8,
      },
      {
        name: 'Sandía',
        description: 'Sandía fresca',
        calories_portion: 30,
        protein_portion: 0.6,
        carbos_portion: 8,
        fats_portion: 0.2,
      },
      {
        name: 'Perca',
        description: 'Filete de perca cocida',
        calories_portion: 96,
        protein_portion: 20,
        carbos_portion: 0,
        fats_portion: 1.5,
      },
      {
        name: 'Fideos de trigo',
        description: 'Fideos de trigo cocidos',
        calories_portion: 131,
        protein_portion: 5,
        carbos_portion: 25,
        fats_portion: 1.1,
      },
      {
        name: 'Pan de centeno',
        description: 'Pan de centeno rebanado',
        calories_portion: 165,
        protein_portion: 6,
        carbos_portion: 33,
        fats_portion: 1.3,
      },
      {
        name: 'Jitomate',
        description: 'Jitomate fresco',
        calories_portion: 18,
        protein_portion: 0.9,
        carbos_portion: 3.9,
        fats_portion: 0.2,
      },
      {
        name: 'Col rizada',
        description: 'Col rizada fresca',
        calories_portion: 36,
        protein_portion: 2.9,
        carbos_portion: 6.7,
        fats_portion: 0.3,
      },
      {
        name: 'Aceitunas',
        description: 'Aceitunas verdes en conserva',
        calories_portion: 115,
        protein_portion: 0.8,
        carbos_portion: 5,
        fats_portion: 10.7,
      },
      {
        name: 'Cuscús integral',
        description: 'Cuscús integral cocido',
        calories_portion: 112,
        protein_portion: 3.8,
        carbos_portion: 23,
        fats_portion: 0.2,
      },
      {
        name: 'Champiñones',
        description: 'Champiñones crudos',
        calories_portion: 15,
        protein_portion: 1.7,
        carbos_portion: 2.3,
        fats_portion: 0.3,
      },
      {
        name: 'Aceite de coco',
        description: 'Aceite de coco virgen',
        calories_portion: 121,
        protein_portion: 0,
        carbos_portion: 0,
        fats_portion: 13.5,
      },
      {
        name: 'Anacardos',
        description: 'Anacardos crudos',
        calories_portion: 155,
        protein_portion: 5,
        carbos_portion: 9,
        fats_portion: 12,
      },
      {
        name: 'Lentejas',
        description: 'Lentejas cocidas',
        calories_portion: 116,
        protein_portion: 9,
        carbos_portion: 20,
        fats_portion: 0.4,
      },
      {
        name: 'Quinoa',
        description: 'Quinoa cocida',
        calories_portion: 120,
        protein_portion: 4.1,
        carbos_portion: 21,
        fats_portion: 1.9,
      },
      {
        name: 'Mango seco',
        description: 'Mango seco deshidratado',
        calories_portion: 319,
        protein_portion: 2.8,
        carbos_portion: 79,
        fats_portion: 0.6,
      },
      {
        name: 'Melón',
        description: 'Melón fresco',
        calories_portion: 34,
        protein_portion: 0.8,
        carbos_portion: 8,
        fats_portion: 0.2,
      },
      {
        name: 'Papaya',
        description: 'Papaya fresca',
        calories_portion: 43,
        protein_portion: 0.5,
        carbos_portion: 11,
        fats_portion: 0.2,
      },
      {
        name: 'Pan de centeno integral',
        description: 'Pan de centeno integral rebanado',
        calories_portion: 165,
        protein_portion: 6,
        carbos_portion: 33,
        fats_portion: 1.3,
      },
      {
        name: 'Pepitas de calabaza',
        description: 'Pepitas de calabaza crudas',
        calories_portion: 90,
        protein_portion: 7,
        carbos_portion: 4,
        fats_portion: 7,
      },
      {
        name: 'Aceitunas negras',
        description: 'Aceitunas negras en conserva',
        calories_portion: 115,
        protein_portion: 0.8,
        carbos_portion: 5,
        fats_portion: 10.7,
      },
      {
        name: 'Ternera',
        description: 'Filete de ternera magra cocido',
        calories_portion: 210,
        protein_portion: 30,
        carbos_portion: 0,
        fats_portion: 9,
      },
      {
        name: 'Sardinas en lata',
        description: 'Sardinas en lata en aceite',
        calories_portion: 208,
        protein_portion: 25,
        carbos_portion: 0,
        fats_portion: 12,
      },
      {
        name: 'Camarones',
        description: 'Camarones cocidos',
        calories_portion: 86,
        protein_portion: 18,
        carbos_portion: 0,
        fats_portion: 1.5,
      },
      {
        name: 'Pasta de sésamo',
        description: 'Pasta de sésamo',
        calories_portion: 89,
        protein_portion: 4,
        carbos_portion: 4,
        fats_portion: 7,
      },
      {
        name: 'Pera seca',
        description: 'Pera seca deshidratada',
        calories_portion: 262,
        protein_portion: 1.4,
        carbos_portion: 69,
        fats_portion: 0.6,
      },
      {
        name: 'Espárragos',
        description: 'Espárragos frescos',
        calories_portion: 20,
        protein_portion: 2.2,
        carbos_portion: 3.9,
        fats_portion: 0.2,
      },
      {
        name: 'Frijoles blancos',
        description: 'Frijoles blancos cocidos',
        calories_portion: 132,
        protein_portion: 9,
        carbos_portion: 24,
        fats_portion: 0.6,
      },
      {
        name: 'Pasta de cacahuate',
        description: 'Pasta de cacahuate',
        calories_portion: 94,
        protein_portion: 4,
        carbos_portion: 3,
        fats_portion: 8,
      },
      {
        name: 'Zumo de naranja',
        description: 'Zumo de naranja natural',
        calories_portion: 45,
        protein_portion: 1,
        carbos_portion: 10,
        fats_portion: 0.2,
      },
      {
        name: 'Tomate seco',
        description: 'Tomate seco deshidratado',
        calories_portion: 258,
        protein_portion: 14,
        carbos_portion: 38,
        fats_portion: 3.7,
      },
      {
        name: 'Uvas',
        description: 'Uvas frescas',
        calories_portion: 69,
        protein_portion: 0.7,
        carbos_portion: 18,
        fats_portion: 0.2,
      },
      {
        name: 'Pechuga de pollo asada',
        description: 'Pechuga de pollo asada sin piel',
        calories_portion: 165,
        protein_portion: 31,
        carbos_portion: 0,
        fats_portion: 3.6,
      },
      {
        name: 'Tofu ahumado',
        description: 'Tofu ahumado',
        calories_portion: 76,
        protein_portion: 8,
        carbos_portion: 1.9,
        fats_portion: 4.8,
      },
      {
        name: 'Salmón fresco',
        description: 'Filete de salmón fresco',
        calories_portion: 220,
        protein_portion: 20,
        carbos_portion: 0,
        fats_portion: 15,
      },
      {
        name: 'Café',
        description: 'Café negro, sin azúcar',
        calories_portion: 2,
        protein_portion: 0.3,
        carbos_portion: 0,
        fats_portion: 0,
      },
      {
        name: 'Té verde',
        description: 'Té verde, sin azúcar',
        calories_portion: 2,
        protein_portion: 0,
        carbos_portion: 0.3,
        fats_portion: 0,
      },
      {
        name: 'Mantequilla de maní',
        description: 'Mantequilla de maní natural',
        calories_portion: 180,
        protein_portion: 8,
        carbos_portion: 7,
        fats_portion: 16,
      },
      {
        name: 'Mantequilla de almendras',
        description: 'Mantequilla de almendras natural',
        calories_portion: 180,
        protein_portion: 6,
        carbos_portion: 7,
        fats_portion: 16,
      },
      {
        name: 'Mantequilla de anacardos',
        description: 'Mantequilla de anacardos natural',
        calories_portion: 180,
        protein_portion: 6,
        carbos_portion: 8,
        fats_portion: 15,
      },
      {
        name: 'Batata',
        description: 'Batata cocida',
        calories_portion: 90,
        protein_portion: 2,
        carbos_portion: 21,
        fats_portion: 0.1,
      },
      {
        name: 'Frijoles pintos',
        description: 'Frijoles pintos cocidos',
        calories_portion: 143,
        protein_portion: 9,
        carbos_portion: 26,
        fats_portion: 0.5,
      },
      {
        name: 'Pan de espelta',
        description: 'Pan de espelta rebanado',
        calories_portion: 135,
        protein_portion: 5,
        carbos_portion: 26,
        fats_portion: 1,
      },
      {
        name: 'Pimiento',
        description: 'Pimiento verde crudo',
        calories_portion: 20,
        protein_portion: 0.9,
        carbos_portion: 4.6,
        fats_portion: 0.2,
      },
      {
        name: 'Arroz integral',
        description: 'Arroz integral cocido',
        calories_portion: 111,
        protein_portion: 2.6,
        carbos_portion: 23,
        fats_portion: 0.9,
      },
      {
        name: 'Queso feta',
        description: 'Queso feta',
        calories_portion: 264,
        protein_portion: 14,
        carbos_portion: 4.1,
        fats_portion: 21,
      },
      {
        name: 'Acelga',
        description: 'Acelga cruda',
        calories_portion: 19,
        protein_portion: 1.8,
        carbos_portion: 3.7,
        fats_portion: 0.2,
      },
      {
        name: 'Mandarina',
        description: 'Mandarina fresca',
        calories_portion: 53,
        protein_portion: 0.8,
        carbos_portion: 13,
        fats_portion: 0.3,
      },
      {
        name: 'Mandarina seca',
        description: 'Mandarina seca deshidratada',
        calories_portion: 300,
        protein_portion: 0.9,
        carbos_portion: 79,
        fats_portion: 0.6,
      },
      {
        name: 'Almeja',
        description: 'Almejas cocidas',
        calories_portion: 148,
        protein_portion: 24,
        carbos_portion: 7,
        fats_portion: 2,
      },
      {
        name: 'Chucrut',
        description: 'Chucrut fermentado',
        calories_portion: 19,
        protein_portion: 0.9,
        carbos_portion: 4.3,
        fats_portion: 0.1,
      },
      {
        name: 'Salsa de soja',
        description: 'Salsa de soja baja en sodio',
        calories_portion: 10,
        protein_portion: 2.2,
        carbos_portion: 1.3,
        fats_portion: 0,
      },
      {
        name: 'Cilantro',
        description: 'Cilantro fresco',
        calories_portion: 23,
        protein_portion: 2.1,
        carbos_portion: 3.7,
        fats_portion: 0.5,
      },
      {
        name: 'Romero',
        description: 'Romero fresco',
        calories_portion: 131,
        protein_portion: 3.3,
        carbos_portion: 20,
        fats_portion: 5.7,
      },
      {
        name: 'Perejil',
        description: 'Perejil fresco',
        calories_portion: 36,
        protein_portion: 2.2,
        carbos_portion: 6.3,
        fats_portion: 0.8,
      },
      {
        name: 'Estragón',
        description: 'Estragón fresco',
        calories_portion: 28,
        protein_portion: 2.5,
        carbos_portion: 5.4,
        fats_portion: 0.7,
      },
      {
        name: 'Espinaca',
        description: 'Espinaca cocida',
        calories_portion: 23,
        protein_portion: 2.9,
        carbos_portion: 3.6,
        fats_portion: 0.4,
      },
      {
        name: 'Albahaca',
        description: 'Albahaca fresca',
        calories_portion: 23,
        protein_portion: 3,
        carbos_portion: 2.7,
        fats_portion: 0.6,
      },
      {
        name: 'Salvia',
        description: 'Salvia fresca',
        calories_portion: 26,
        protein_portion: 3,
        carbos_portion: 2.6,
        fats_portion: 0.6,
      },
      {
        name: 'Orégano',
        description: 'Orégano seco',
        calories_portion: 265,
        protein_portion: 9,
        carbos_portion: 69,
        fats_portion: 4.3,
      },
      {
        name: 'Tomillo',
        description: 'Tomillo seco',
        calories_portion: 276,
        protein_portion: 10,
        carbos_portion: 64,
        fats_portion: 8,
      },
      {
        name: 'Cebolla verde',
        description: 'Cebolla verde fresca',
        calories_portion: 32,
        protein_portion: 1.3,
        carbos_portion: 7.6,
        fats_portion: 0.2,
      },
      {
        name: 'Ajo en polvo',
        description: 'Ajo en polvo',
        calories_portion: 263,
        protein_portion: 16,
        carbos_portion: 64,
        fats_portion: 0.5,
      },
      {
        name: 'Espinacas congeladas',
        description: 'Espinacas congeladas',
        calories_portion: 23,
        protein_portion: 2.9,
        carbos_portion: 3.6,
        fats_portion: 0.4,
      },
      {
        name: 'Harina de trigo integral',
        description: 'Harina de trigo integral',
        calories_portion: 364,
        protein_portion: 13,
        carbos_portion: 72,
        fats_portion: 2,
      },
      {
        name: 'Azúcar de coco',
        description: 'Azúcar de coco',
        calories_portion: 380,
        protein_portion: 1.2,
        carbos_portion: 92,
        fats_portion: 0.5,
      },
      {
        name: 'Mantequilla de cacao',
        description: 'Mantequilla de cacao',
        calories_portion: 898,
        protein_portion: 0,
        carbos_portion: 0,
        fats_portion: 99.9,
      },
      {
        name: 'Pan de trigo sarraceno',
        description: 'Pan de trigo sarraceno rebanado',
        calories_portion: 202,
        protein_portion: 5,
        carbos_portion: 39,
        fats_portion: 1.3,
      },
      {
        name: 'Mijo',
        description: 'Mijo cocido',
        calories_portion: 205,
        protein_portion: 4.2,
        carbos_portion: 41,
        fats_portion: 1.2,
      },
      {
        name: 'Ciruela seca',
        description: 'Ciruela seca deshidratada',
        calories_portion: 240,
        protein_portion: 2.3,
        carbos_portion: 63,
        fats_portion: 0.4,
      },
      {
        name: 'Arroz blanco',
        description: 'Arroz blanco cocido',
        calories_portion: 129,
        protein_portion: 2.6,
        carbos_portion: 28,
        fats_portion: 0.3,
      },
      {
        name: 'Arroz basmati',
        description: 'Arroz basmati cocido',
        calories_portion: 121,
        protein_portion: 2.6,
        carbos_portion: 25,
        fats_portion: 0.2,
      },
      {
        name: 'Arroz salvaje',
        description: 'Arroz salvaje cocido',
        calories_portion: 101,
        protein_portion: 3,
        carbos_portion: 21,
        fats_portion: 0.3,
      },
      {
        name: 'Aguacate',
        description: 'Aguacate fresco',
        calories_portion: 160,
        protein_portion: 2,
        carbos_portion: 9,
        fats_portion: 14,
      },
      {
        name: 'Pepinillo',
        description: 'Pepinillo encurtido',
        calories_portion: 12,
        protein_portion: 0.4,
        carbos_portion: 2.4,
        fats_portion: 0.1,
      },
      {
        name: 'Pasta de albaricoque',
        description: 'Pasta de albaricoque',
        calories_portion: 241,
        protein_portion: 4.2,
        carbos_portion: 62,
        fats_portion: 0.1,
      },
      {
        name: 'Pasta de higo',
        description: 'Pasta de higo',
        calories_portion: 267,
        protein_portion: 2.5,
        carbos_portion: 67,
        fats_portion: 0.6,
      },
      {
        name: 'Pasta de dátil',
        description: 'Pasta de dátil',
        calories_portion: 282,
        protein_portion: 1.8,
        carbos_portion: 75,
        fats_portion: 0.4,
      },
      {
        name: 'Pasta de manzana',
        description: 'Pasta de manzana',
        calories_portion: 284,
        protein_portion: 0.8,
        carbos_portion: 75,
        fats_portion: 0.2,
      },
      {
        name: 'Pasta de plátano',
        description: 'Pasta de plátano',
        calories_portion: 320,
        protein_portion: 2.3,
        carbos_portion: 82,
        fats_portion: 0.3,
      },
      {
        name: 'Pasta de pera',
        description: 'Pasta de pera',
        calories_portion: 292,
        protein_portion: 0.5,
        carbos_portion: 76,
        fats_portion: 0.3,
      },
      {
        name: 'Pasta de ciruela',
        description: 'Pasta de ciruela',
        calories_portion: 248,
        protein_portion: 1.6,
        carbos_portion: 63,
        fats_portion: 0.2,
      },
      {
        name: 'Pasta de mango',
        description: 'Pasta de mango',
        calories_portion: 319,
        protein_portion: 2.8,
        carbos_portion: 79,
        fats_portion: 0.6,
      },
      {
        name: 'Pasta de melocotón',
        description: 'Pasta de melocotón',
        calories_portion: 292,
        protein_portion: 0.7,
        carbos_portion: 76,
        fats_portion: 0.3,
      },
      {
        name: 'Pasta de mora',
        description: 'Pasta de mora',
        calories_portion: 253,
        protein_portion: 1.5,
        carbos_portion: 66,
        fats_portion: 0.4,
      },
      {
        name: 'Pasta de cereza',
        description: 'Pasta de cereza',
        calories_portion: 250,
        protein_portion: 1,
        carbos_portion: 65,
        fats_portion: 0.2,
      },
      {
        name: 'Pasta de frambuesa',
        description: 'Pasta de frambuesa',
        calories_portion: 258,
        protein_portion: 1.5,
        carbos_portion: 66,
        fats_portion: 0.4,
      },
      {
        name: 'Pasta de arándano',
        description: 'Pasta de arándano',
        calories_portion: 264,
        protein_portion: 1.5,
        carbos_portion: 68,
        fats_portion: 0.4,
      },
      {
        name: 'Pasta de grosella',
        description: 'Pasta de grosella',
        calories_portion: 254,
        protein_portion: 1.5,
        carbos_portion: 66,
        fats_portion: 0.4,
      },
      {
        name: 'Pasta de guayaba',
        description: 'Pasta de guayaba',
        calories_portion: 263,
        protein_portion: 1.4,
        carbos_portion: 68,
        fats_portion: 0.4,
      },
      {
        name: 'Pasta de naranja',
        description: 'Pasta de naranja',
        calories_portion: 257,
        protein_portion: 1.2,
        carbos_portion: 67,
        fats_portion: 0.3,
      },
      {
        name: 'Pasta de uva',
        description: 'Pasta de uva',
        calories_portion: 277,
        protein_portion: 1.1,
        carbos_portion: 72,
        fats_portion: 0.3,
      },
      {
        name: 'Pasta de caqui',
        description: 'Pasta de caqui',
        calories_portion: 254,
        protein_portion: 1.1,
        carbos_portion: 66,
        fats_portion: 0.3,
      },
      {
        name: 'Pasta de piña',
        description: 'Pasta de piña',
        calories_portion: 257,
        protein_portion: 1,
        carbos_portion: 67,
        fats_portion: 0.2,
      },
      {
        name: 'Pasta de papaya',
        description: 'Pasta de papaya',
        calories_portion: 257,
        protein_portion: 0.9,
        carbos_portion: 68,
        fats_portion: 0.2,
      },
      {
        name: 'Pasta de limón',
        description: 'Pasta de limón',
        calories_portion: 252,
        protein_portion: 0.7,
        carbos_portion: 66,
        fats_portion: 0.1,
      },
      {
        name: 'Pasta de lima',
        description: 'Pasta de lima',
        calories_portion: 257,
        protein_portion: 0.7,
        carbos_portion: 67,
        fats_portion: 0.1,
      },
      {
        name: 'Pasta de fruta de la pasión',
        description: 'Pasta de fruta de la pasión',
        calories_portion: 267,
        protein_portion: 0.6,
        carbos_portion: 70,
        fats_portion: 0.2,
      },
      {
        name: 'Pasta de durazno',
        description: 'Pasta de durazno',
        calories_portion: 257,
        protein_portion: 0.5,
        carbos_portion: 68,
        fats_portion: 0.1,
      },
      {
        name: 'Pasta de lichi',
        description: 'Pasta de lichi',
        calories_portion: 257,
        protein_portion: 0.5,
        carbos_portion: 67,
        fats_portion: 0.1,
      },
      {
        name: 'Pasta de maracuyá',
        description: 'Pasta de maracuyá',
        calories_portion: 267,
        protein_portion: 0.4,
        carbos_portion: 70,
        fats_portion: 0.1,
      },
      {
        name: 'Pasta de pera asiática',
        description: 'Pasta de pera asiática',
        calories_portion: 257,
        protein_portion: 0.3,
        carbos_portion: 68,
        fats_portion: 0.1,
      },
      {
        name: 'Pasta de kiwi',
        description: 'Pasta de kiwi',
        calories_portion: 267,
        protein_portion: 0.3,
        carbos_portion: 70,
        fats_portion: 0.1,
      },
      {
        name: 'Pasta de plátano macho',
        description: 'Pasta de plátano macho',
        calories_portion: 257,
        protein_portion: 0.3,
        carbos_portion: 68,
        fats_portion: 0,
      },
      {
        name: 'Pasta de ciruela umeboshi',
        description: 'Pasta de ciruela umeboshi',
        calories_portion: 263,
        protein_portion: 0.2,
        carbos_portion: 69,
        fats_portion: 0,
      },
      {
        name: 'Pasta de piña y coco',
        description: 'Pasta de piña y coco',
        calories_portion: 257,
        protein_portion: 0.2,
        carbos_portion: 67,
        fats_portion: 0,
      },
      {
        name: 'Pasta de uva y kiwi',
        description: 'Pasta de uva y kiwi',
        calories_portion: 267,
        protein_portion: 0.2,
        carbos_portion: 70,
        fats_portion: 0,
      },
      {
        name: 'Pasta de mango y maracuyá',
        description: 'Pasta de mango y maracuyá',
        calories_portion: 267,
        protein_portion: 0.2,
        carbos_portion: 70,
        fats_portion: 0,
      },
      {
        name: 'Pasta de maracuyá y kiwi',
        description: 'Pasta de maracuyá y kiwi',
        calories_portion: 267,
        protein_portion: 0.2,
        carbos_portion: 70,
        fats_portion: 0,
      },
      {
        name: 'Pasta de mango y papaya',
        description: 'Pasta de mango y papaya',
        calories_portion: 267,
        protein_portion: 0.2,
        carbos_portion: 70,
        fats_portion: 0,
      },
    ]);
    await repository.save(aliment);
  }
}
